//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit_Card_Validation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CreditCardDBEntities1 : DbContext
    {
        public CreditCardDBEntities1()
            : base("name=CreditCardDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCreditCardsList> tblCreditCardsLists { get; set; }
    
        public virtual ObjectResult<sp_CreditCardNumberValidator_Result> sp_CreditCardNumberValidator(string creditCard)
        {
            var creditCardParameter = creditCard != null ?
                new ObjectParameter("creditCard", creditCard) :
                new ObjectParameter("creditCard", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CreditCardNumberValidator_Result>("sp_CreditCardNumberValidator", creditCardParameter);
        }
    }
}
