//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit_Card_Validation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreditCardsList
    {
        public int fldSeqNo { get; set; }
        public string fldCardNumber { get; set; }
        public string fldExpiryDate { get; set; }
        public string fldCardType { get; set; }
    }
}
